---
## Kernel security hardening from
## https://madaidans-insecurities.github.io/guides/linux-hardening.html

- name: Kernel - Disable unused kernel modules
  ansible.builtin.copy:
    src: kernel_module_hardening.conf
    dest: /etc/modprobe.d/kernel_module_hardening.conf
    owner: root
    group: root
    mode: '644'
  notify: Restart system

- name: Kernel - Apply sysctl kernel hardening
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_hardening }}'

- name: Kernel - Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when:
    network_ipv6_disabled | bool
